"""Creating ConversationHistory

Revision ID: 573717537f79
Revises: 
Create Date: 2025-11-21 22:02:42.252758

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '573717537f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_guild_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discord_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_history_discord_channel_id'), 'conversation_history', ['discord_channel_id'], unique=False)
    op.create_index(op.f('ix_conversation_history_discord_guild_id'), 'conversation_history', ['discord_guild_id'], unique=False)
    op.create_index(op.f('ix_conversation_history_discord_user_id'), 'conversation_history', ['discord_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_history_discord_user_id'), table_name='conversation_history')
    op.drop_index(op.f('ix_conversation_history_discord_guild_id'), table_name='conversation_history')
    op.drop_index(op.f('ix_conversation_history_discord_channel_id'), table_name='conversation_history')
    op.drop_table('conversation_history')
    # ### end Alembic commands ###